name: Build Go macOS Binaries for Orion Release

on: 
  release:
    types: [created]

jobs:

  build-macOS:
    name: Build Binary for macOS
    runs-on: macos-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.14
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi
    - name: Get Release
      id: get_release
      uses: bruceadams/get-release@v1.2.1
      env:
        GITHUB_TOKEN: ${{ github.token }}

    - name: Build macOS Binary
      run: go build -v .

    - name: Test macOS Binary
      run: go test -v .
      
    - name: ls
      run: ls -la
    
    - name: Upload macOS Binary to Release
      uses: actions/upload-release-asset@v1.0.2
      with:
        upload_url: ${{ steps.get_release.outputs.upload_url }}
        asset_name: Orion
        asset_path: Orion
        asset_content_type: application/octet-stream
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
